[package]
name = "jsdom"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "A fast virtual dom"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
resast = "0.5.0"
ressa = "0.8.1"
